# Generated by Django 6.0.4 on 2026-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor')], default='author', max_length=20),
        ),
    ]
