# Generated by Django 6.0.4 on 2026-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department_user_designation_user_expertise_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('editor-in-chief', 'Editor-in-Chief'), ('managing-editor', 'Managing Editor'), ('associate-editor', 'Associate Editor'), ('editorial-assistant', 'Editorial Assistant')], default='author', max_length=20),
        ),
    ]
