# Generated by Django 6.0.4 on 2026-04-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='abstract',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='keywords',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='paper_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
