# Generated by Django 6.0.4 on 2026-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='area_of_research',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='file',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='previous_paper_id',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='state',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='final_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='review_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='paper_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(default='submitted', max_length=20),
        ),
    ]
