# Generated by Django 6.0.4 on 2026-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_remove_manuscript_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manuscripts/'),
        ),
    ]
