# Generated by Django 6.0.4 on 2026-04-28 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_manuscript_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='desk_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('desk_review_approved', 'Desk Review Approved'), ('desk_review_rejected', 'Desk Review Rejected'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='DeskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved for Review'), ('rejected', 'Rejected at Desk'), ('major_revision', 'Major Revision Required')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Managing Editor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desk_reviews_managed', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desk_review', to='manuscripts.manuscript')),
            ],
        ),
    ]
