# Generated by Django 6.0.4 on 2026-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_manuscript_assigned_by_manuscript_desk_review_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='desk_review_notes',
            new_name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='submitted', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeskReview',
        ),
    ]
